workflows:  
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "MovieCatalogue/MovieCatalogue.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "MovieCatalogue" # Isikan nama scheme project Anda.
    scripts:
      - name: Install Cocoapods
        script: |
          gem install cocoapods
      - name: Pod install
        script: |
          pod install --project-directory=MovieCatalogue
      - name: Run tests
        script: |
          xcodebuild \
          clean build \
          -arch arm64
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO          
      - name: Build debug app
        script: |
          xcodebuild clean build -project "$XCODE_PROJECT" \
          -arch arm64
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO          
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - aditt7116@gmail.com # Isikan email untuk notifikasi status building.