# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.0'

use_frameworks!
workspace 'MovieCatalogueWithModular'

target 'MovieCatalogue' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for MovieCatalogue
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'RealmSwift', '~>10'
  pod 'SDWebImageSwiftUI'
  pod 'Core', :git => "https://github.com/tbadhit/Modularization-Core-Module.git"

  target 'MovieCatalogueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieCatalogueUITests' do
    # Pods for testing
  end

end

target 'Movie' do
  project '../Modules/Movie/Movie'
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'RealmSwift', '~>10'
  pod 'Core', :git => "https://github.com/tbadhit/Modularization-Core-Module.git"
end

target 'Home' do
  project '../Modules/Home/Home'
  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'
  pod 'Core', :git => "https://github.com/tbadhit/Modularization-Core-Module.git"
end

target 'Favorite' do
  project '../Modules/Favorite/Favorite'
  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'
  pod 'Core', :git => "https://github.com/tbadhit/Modularization-Core-Module.git"
end

target 'Search' do
  project '../Modules/Search/Search'
  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'
  pod 'Core', :git => "https://github.com/tbadhit/Modularization-Core-Module.git"
end

target 'Profile' do
  project '../Modules/Profile/Profile'
  pod 'SwiftLint'
end

target 'Detail' do
  project '../Modules/Detail/Detail'
  pod 'SwiftLint'
  pod 'SDWebImageSwiftUI'
  pod 'Core', :git => "https://github.com/tbadhit/Modularization-Core-Module.git"
end
